
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Sengarofficial/datasets_artifact/raw/master/nasa_predictiive.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  

data_cleaning:
  root_dir: artifacts/data_cleaning
  unzip_data_dir_train: artifacts/data_ingestion/CMaps/train_FD001.txt
  
data_validation:
  root_dir: artifacts/data_validation
  clean_data_dir: artifacts/data_cleaning/train.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_cleaning/train.csv
  scaler_name: scaler.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_scaled.csv
  test_data_path: artifacts/data_transformation/test_scaled.csv
  model_name: model.joblib
  imputer_name: imputer.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_scaled.csv
  test_y: artifacts/model_trainer/test_y.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
